export const CHARACTERS_GET_LIST = 'CHARACTERS_GET_LIST';
export const CHARACTERS_GET_CHARACTER_DETAIL = 'CHARACTERS_GET_CHARACTER_DETAIL';
export const CHARACTERS_GET_MORE_CHARACTERS = 'CHARACTERS_GET_MORE_CHARACTERS';

// Key Store
export const CHARACTERS = 'characters';
